version: '3.8'

services:
  go:
    container_name: go
    build: 
      context: ./goland
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./goland/src
        target: /go/src
    networks:
      - golang_test_network

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    hostname: test
    tty: true
    platform: linux/x86_64
    environment:
      MYSQL_USER: test_user
      MYSQL_DATABASE: test_database
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    networks:
      - golang_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true